// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfrh__9pFdHp9FByRqifGIU3dzvky8FU',
    appId: '1:59537575004:web:6ba671ccb18666fc586a99',
    messagingSenderId: '59537575004',
    projectId: 'prabitha-operations',
    authDomain: 'prabitha-operations.firebaseapp.com',
    databaseURL: 'https://prabitha-operations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prabitha-operations.firebasestorage.app',
    measurementId: 'G-1RYYRKCKNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbGp9eHyrsj0jfRlRN9uLu-P_xu91b2SE',
    appId: '1:59537575004:android:624889ddb774f899586a99',
    messagingSenderId: '59537575004',
    projectId: 'prabitha-operations',
    databaseURL: 'https://prabitha-operations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prabitha-operations.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKuBJxcQ_HcOKFwpZOfRK_YAwkZbRVA3o',
    appId: '1:59537575004:ios:bd6321a975805609586a99',
    messagingSenderId: '59537575004',
    projectId: 'prabitha-operations',
    databaseURL: 'https://prabitha-operations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prabitha-operations.firebasestorage.app',
    iosBundleId: 'com.factory.factoryApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKuBJxcQ_HcOKFwpZOfRK_YAwkZbRVA3o',
    appId: '1:59537575004:ios:7fd2c02a52042a33586a99',
    messagingSenderId: '59537575004',
    projectId: 'prabitha-operations',
    databaseURL: 'https://prabitha-operations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prabitha-operations.firebasestorage.app',
    iosBundleId: 'com.factory.factoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmfrh__9pFdHp9FByRqifGIU3dzvky8FU',
    appId: '1:59537575004:web:0d1ba9d5f2451605586a99',
    messagingSenderId: '59537575004',
    projectId: 'prabitha-operations',
    authDomain: 'prabitha-operations.firebaseapp.com',
    databaseURL: 'https://prabitha-operations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prabitha-operations.firebasestorage.app',
    measurementId: 'G-QGBBQEH9XK',
  );
}
